require('reflect-metadata');
const crypto = require('crypto');
const { NestFactory } = require('@nestjs/core');
const { ValidationPipe } = require('@nestjs/common');
const { getConnectionToken } = require('@nestjs/mongoose');
const { DocumentBuilder, SwaggerModule } = require('@nestjs/swagger');
const { AllExceptionsFilter } = require('../../dist/common/filters/all-exceptions.filter');

// Never use .env credentials or an existing database for mutable review tests.
async function openFixture() {
  const database = `proyecto1_review_${crypto.randomBytes(8).toString('hex')}`;
  const password = `Fixture9${crypto.randomBytes(12).toString('hex')}`;
  Object.assign(process.env, {
    NODE_ENV: 'test', PORT: '43101',
    MONGODB_URI: `mongodb://localhost:27017/${database}?replicaSet=rs0&directConnection=true`,
    JWT_SECRET: crypto.randomBytes(32).toString('hex'), JWT_EXPIRES_IN_SECONDS: '3600',
    ADMIN_EMAIL: 'review-admin@example.invalid', ADMIN_PASSWORD: password,
  });
  const { AppModule } = require('../../dist/app.module');
  const app = await NestFactory.create(AppModule, { logger: false, abortOnError: false });
  app.setGlobalPrefix('api/v1');
  app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true, forbidNonWhitelisted: true }));
  app.useGlobalFilters(new AllExceptionsFilter());
  const swagger = SwaggerModule.createDocument(app, new DocumentBuilder().setTitle('API Gestion Academica').setVersion('1.0').addBearerAuth().build());
  await app.listen(0, '127.0.0.1');
  const connection = app.get(getConnectionToken());
  const baseUrl = await app.getUrl();
  const close = async () => {
    // Delete only documents in the database generated by this invocation, never drop a database.
    if (connection.name !== database || !/^proyecto1_review_[a-f0-9]{16}$/.test(database)) throw new Error('Unsafe fixture cleanup target');
    try {
      for (const c of await connection.db.listCollections().toArray()) await connection.db.collection(c.name).deleteMany({});
    } finally { await app.close(); }
  };
  return { app, connection, database, baseUrl, password, swagger, close };
}
module.exports = { openFixture };
